# Compilando o arquivo GeradorCaverna.c para GeradorCaverna.o
all: GeradorCaverna.o

GeradorCaverna.o: GeradorCaverna.c
	gcc -c GeradorCaverna.c -o GeradorCaverna.o

# Limpeza dos arquivos compilados
clean:
	rm -f GeradorCaverna.o
